<a href="https://colab.research.google.com/github/nguyenvuonghongvy/TH_DeepLearning/blob/main/Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # [cite: 10, 18]
#cách 1
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)
my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)
#cách 2
a = np.array([1, 9, 15, 39])
print(a)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
[ 1  9 15 39]


In [2]:
#array 2 chiều
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [3]:
#array 3 chiều
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(d)
print(d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
#3.4 tạo array với giá trị 0 hoặc 1
e = np.zeros((2, 3))