<a href="https://colab.research.google.com/github/nguyenvuonghongvy/TH_DeepLearning/blob/main/Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY


## TẠO ARRAY 1 CHIỀU


In [1]:
import numpy as np # [cite: 10, 18]
#cách 1
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)
my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)
#cách 2
a = np.array([1, 9, 15, 39])
print(a)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
[ 1  9 15 39]


## TẠO ARRAY 2 CHIỀU

In [2]:
#array 2 chiều
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


## TẠO ARRAY 3 CHIỀU

In [3]:
#array 3 chiều
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(d)
print(d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


## 3.4. Tạo Array với giá trị ban đầu là 0 hoặc 1

In [4]:
#3.4 tạo array với giá trị 0 hoặc 1
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix:\n', e)
print('One matrix:\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 3.5. Reshape và Flatten ma trận

### 3.5.1. Reshape thay đổi kích thước ma trận

In [5]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)
f = e.reshape(3, 2)
print(f)
g = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(g)
print(g.shape)
h = g.reshape(3, 4)
print('reshape (3,4)\n', h)
j = g.reshape(3, 2, 2)
print('reshape (3, 2 ,2)\n', j)
k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
(4, 3)
reshape (3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2 ,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


### 3.5.2. Platten là chuyển array nhiều chiều về 1 chiều

In [6]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)
g = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


## 3.6. Thêm dòng dữ liệu với hstack và vstack


In [7]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


## 3.7. Sinh mảng số ngẫu nhiên

### 3.7.1. Sinh mảng số nguyên ngẫu nhiên

In [8]:
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [37  5 66 36 91]
Random 2-D array
 [[72 41 34 38]
 [77 89 88 27]
 [38 24 47 92]]
Random 3-D array
 [[[73 68 37]
  [10 36 34]
  [75 32 62]
  [73 51  0]]

 [[24 91 99]
  [62 98 48]
  [88 88 13]
  [33 80 69]]

 [[36 74  2]
  [27 82 61]
  [46 27 20]
  [63 60 62]]]


### 3.7.2. Sinh mảng số thực trong khoảng [0, 1]


In [9]:
a = np.random.rand(5)
print('Random 1-D array\n', a)
b = np.random.rand(3, 4)
print('Random 2-D array\n', b)
c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.13026588 0.86646001 0.95106017 0.78655576 0.28869048]
Random 2-D array
 [[0.40264214 0.24394873 0.54800403 0.67179146]
 [0.19161919 0.93393901 0.80986244 0.93219186]
 [0.55931082 0.80383891 0.73304432 0.31772622]]
Random 3-D array
 [[[0.11951939 0.98135857 0.43096993]
  [0.90829084 0.58767105 0.3967808 ]
  [0.11889499 0.57401157 0.31110037]
  [0.46728162 0.83640703 0.96922955]]

 [[0.02248494 0.61036971 0.49393516]
  [0.43313356 0.69976483 0.18733592]
  [0.12689149 0.71343987 0.59766432]
  [0.99642254 0.93403263 0.80480558]]

 [[0.90662865 0.27628776 0.01653759]
  [0.70962105 0.70518632 0.8431971 ]
  [0.88467308 0.41594264 0.22822807]
  [0.48537131 0.02026451 0.57863802]]]


### 3.7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

In [10]:
a = np.random.normal(5, 0.5, 10)
print(a)

[5.56332641 5.62961512 5.33368718 4.5897675  5.41013932 4.90995955
 4.71090422 4.70851478 4.24572047 5.78843747]


### 3.7.4. Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [11]:
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

16
[[ 2 10  2  2  6]
 [ 4 14 16  6  8]
 [20 14  6  4 12]]


## 3.8. Thay đổi giá trị của ma trận


In [12]:
A = np.matrix(np.ones((5,5)))
print('The matrix\n', A)
np.array(A)[2] = 2
print('Change values of third row with array\n', A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 3.9. Sinh dãy số theo khoảng cho trước

### 3.9.1. Dùng hàm arange

In [13]:
a = np.arange(1, 20)
print(a)
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


### 3.9.2. Dùng hàm linspace


In [14]:
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


## 3.10. Index và slice

In [15]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])
print('Second column:', a[:, 1])
print('first column', a[:, 0])
print('First two values of second row:', a[1, 2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column [1 4]
First two values of second row: 6


# PANDAS

## 6. TÌM HIỂU ĐỐI TƯỢNG SERIES


In [17]:
import pandas as pd
a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


## 7. TẠO ĐỐI TƯỢNG DATAFRAME

### Chuyển đổi từ mảng dạng Numpy sang Pandas và ngược lại

In [18]:
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame: \n', df_h)

numpy_h = np.array(df_h)
print('Numpy array: \n', numpy_h)

DataFrame: 
    0  1
0  1  2
1  3  4
Numpy array: 
 [[1 2]
 [3 4]]


### Tạo DataFrame mảng 2-chiều có tên cột

In [19]:
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [20]:
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())
print('Chọn cột so1\n', df['so1'])
print('Chọn nhiều dòng\n', df[0:3])
print('Chọn nhiều cột\n', df[['so1', 'so3']])
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, 2])
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0 -0.029088 -1.105934 -0.032164 -2.054944
1 -0.794418 -0.024579 -1.221358  0.618361
2  1.504301  1.068678  0.746443 -1.081573
3  0.374073 -0.161365  0.084607 -1.479543
4  1.410467 -0.812059  0.570703  0.453458
Chọn cột so1
 0    -0.029088
1    -0.794418
2     1.504301
3     0.374073
4     1.410467
5    -0.015196
6    -1.771620
7    -0.641229
8    -1.183364
9    -0.558939
10   -0.335141
11   -0.443975
12   -2.004067
13    0.263267
14   -0.671758
15    1.452093
16   -0.211800
17   -0.308254
18   -0.202436
19   -0.216182
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0 -0.029088 -1.105934 -0.032164 -2.054944
1 -0.794418 -0.024579 -1.221358  0.618361
2  1.504301  1.068678  0.746443 -1.081573
Chọn nhiều cột
          so1       so3
0  -0.029088 -0.032164
1  -0.794418 -1.221358
2   1.504301  0.746443
3   0.374073  0.084607
4   1.410467  0.570703
5  -0.015196  0.469218
6  -1.771620  0.386334
7  -0.641229 -0.590348


### 7.1. Nối nhiều DataFrame

In [21]:
df1 = pd.DataFrame({'Name': ['John', 'Smith', 'Paul'],
                    'Age': [25, 30, 50]},
                   index=[0, 1, 2])

df2 = pd.DataFrame({'Name': ['Adam', 'Smith'],
                    'Age': [26, 11]},
                   index=[3, 4])
df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)
print('Drop duplicatevalues in DataFrame\n', df_concat.drop_duplicates('Name'))
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11
